services:
  postgres:
    image: 'postgres:latest'
    volumes:
      - ./docker/init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      - 'POSTGRES_DB=mydatabase'
      - 'POSTGRES_PASSWORD=secret'
      - 'POSTGRES_USER=myuser'
    ports:
      - '5432:5432'
